# Dependabot configuration file
version: 2
updates:
  # Ruby gems updates
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "all"
    assignees:
      - "djdefi"
    labels:
      - "dependencies"
      - "ruby"
    commit-message:
      prefix: "deps"
      include: "scope"
    
  # GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
    
  # Node.js dependencies (if any in the future)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: "main"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "javascript"
    commit-message:
      prefix: "deps"
      include: "scope"
