name: Test PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: Install dependencies
        run: bundle install

      - name: Run script-new.rb
        run: ruby script-new.rb

      - name: Validate ERB templates
        run: |
          erb -x -T '-' standings.html.erb | ruby -c
          erb -x -T '-' today.html.erb | ruby -c
